# Generated by Django 5.2.5 on 2025-08-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A short, URL-friendly version of the name.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('calendar', 'ICS Calendar')], max_length=10)),
                ('text_content', models.TextField(blank=True, help_text='Enter text content for the slide.')),
                ('image_content', models.ImageField(blank=True, help_text='Upload an image for the slide.', upload_to='images/')),
                ('video_content', models.FileField(blank=True, help_text='Upload a video for the slide.', upload_to='videos/')),
                ('calendar_url', models.URLField(blank=True, help_text='Enter the URL for an ICS calendar.')),
                ('duration', models.PositiveIntegerField(default=10, help_text='Duration to display the slide in seconds.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the slide in the slideshow.')),
                ('slide_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='slideshow.slidedeck')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
