# Generated by Django 5.2.5 on 2025-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedeck',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
