# Generated by Django 5.2.5 on 2025-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0002_slidedeck_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text="Enter the YouTube Video ID (e.g., 'dQw4w9WgXcQ').", max_length=50),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('youtube', 'YouTube Video'), ('calendar', 'ICS Calendar')], max_length=15),
        ),
    ]
