# Generated by Django 5.2.5 on 2025-08-28 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0003_slide_youtube_video_id_alter_slide_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(help_text='A unique identifier for the device, e.g., a MAC address.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text="A friendly name for the device, e.g., 'Lobby Display'", max_length=100)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='The last time this device sent a heartbeat.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='rss_feed_url',
            field=models.URLField(blank=True, help_text='Enter the URL for an RSS news feed.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='weather_location',
            field=models.CharField(blank=True, help_text="e.g., 'Cheyenne,US'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('youtube', 'YouTube Video'), ('calendar', 'ICS Calendar'), ('weather', 'Weather'), ('rss', 'RSS Feed')], max_length=15),
        ),
    ]
