# Generated by Django 5.2.5 on 2025-08-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0004_device_slide_rss_feed_url_slide_weather_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='weather_location',
        ),
        migrations.AddField(
            model_name='slide',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='e.g., 41.139981', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='e.g., -104.820244', max_digits=9, null=True),
        ),
    ]
