# Generated by Django 5.2.5 on 2025-08-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0005_remove_slide_weather_location_slide_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='api_key',
            field=models.CharField(blank=True, help_text='OpenWeatherMap API Key', max_length=100, null=True),
        ),
    ]
