# Generated by Django 5.2.5 on 2025-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0006_slide_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='calendar_url',
            field=models.URLField(blank=True, help_text='Enter the URL for an ICS calendar or the HTML calendar link.'),
        ),
    ]
