# Generated by Django 5.2.5 on 2025-08-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0008_slide_calendar_display_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='calendar_display_style',
            field=models.CharField(choices=[('ics_week', 'ICS Weekly Agenda'), ('html_embed', 'HTML Full Page Embed'), ('ics_today', "ICS Today's Agenda")], default='ics_week', help_text='Choose how to display the calendar.', max_length=20),
        ),
    ]
