# Generated by Django 5.2.5 on 2025-09-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0009_alter_slide_calendar_display_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_slidedeck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='slideshow.slidedeck'),
        ),
    ]
